configurar deploy

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -4,7 +4,7 @@ on:
   push:
     branches: [ "main", "develop" ]
   pull_request:
-    branches: [ "main", "develop" ]
+    branches: [ "main" ]
 
 jobs:
   build:
@@ -79,64 +79,76 @@ jobs:
       run: |
         echo "Coverage Percentage: ${{ steps.coverage.outputs.coverage_percentage }}%"
 
-  ## Falta ajustar as variaveis e secrets para a api de pedidos
-  # deploy:
-  #   name: Deploy
-  #   runs-on: ubuntu-latest
-  #   needs: build
-  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+  # Falta ajustar as variaveis e secrets para a api de pedidos
+  deploy:
+    name: Deploy
+    runs-on: ubuntu-latest
+    needs: build
+    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
     
-  #   steps:
-  #     - name: Checkout
-  #       uses: actions/checkout@v3
-  #     - name: Configure AWS credentials
-  #       uses: aws-actions/configure-aws-credentials@v3
-  #       with:
-  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  #         aws-session-token: ${{ secrets.AWS_SECRET_ACCESS_TOKEN }}
-  #         aws-region: ${{ vars.AWS_REGION }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v3
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-session-token: ${{ secrets.AWS_SECRET_ACCESS_TOKEN }}
+          aws-region: ${{ vars.AWS_REGION }}
 
-  #     - name: Login to Amazon ECR
-  #       id: login-ecr
-  #       uses: aws-actions/amazon-ecr-login@v2
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v2
       
-  #     - name: Set up Docker
-  #       uses: docker/setup-buildx-action@v2
+      - name: Set up Docker
+        uses: docker/setup-buildx-action@v2
       
-  #     - name: Build, tag, and push image to Amazon ECR
-  #       id: build-image
-  #       env:
-  #         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-  #         ECR_REPOSITORY: ecr-${{ vars.PROJECT_NAME }}-api-products
-  #         IMAGE_TAG: ${{ github.sha }}
-  #       run: |
-  #         docker build -f src/infra.web-api/SnackTech.Products.Driver.API/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG src
-  #         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
-  #         echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
+      - name: Build, tag, and push image to Amazon ECR
+        id: build-image
+        env:
+          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          ECR_REPOSITORY: ecr-${{ vars.PROJECT_NAME }}-api-orders
+          IMAGE_TAG: ${{ github.sha }}
+        run: |
+          docker build -f src/infra.web-api/SnackTech.Orders.Driver.API/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG src
+          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
         
-  #     - name: Install Kubectl
-  #       run: |
-  #         curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
-  #         chmod +x kubectl
-  #         sudo mv kubectl /usr/local/bin/
+      - name: Install Kubectl
+        run: |
+          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
+          chmod +x kubectl
+          sudo mv kubectl /usr/local/bin/
 
-  #     - name: Configure Kubectl
-  #       run: |
-  #         aws eks --region ${{ vars.AWS_REGION }} update-kubeconfig --name ${{ vars.PROJECT_NAME }}
+      - name: Configure Kubectl
+        run: |
+          aws eks --region ${{ vars.AWS_REGION }} update-kubeconfig --name ${{ vars.PROJECT_NAME }}
       
-  #     - name: Replace connection string value
-  #       env:
-  #         MSSQL_CONNECTION_STRING: Server=${{ secrets.DB_INSTANCE_PRODUTOS }},${{ vars.DB_PORT }};Database=SnackTechProductsDb;User=${{ secrets.DB_UID_PRODUTOS }};Password=${{ secrets.DB_PASSWORD_PRODUTOS }};TrustServerCertificate=True
-  #       run: |
-  #         CONNECTION_STRING_B64=$(echo "$MSSQL_CONNECTION_STRING" | base64)
-  #         yq e '.data["msslq-connection-string"] = "'"$CONNECTION_STRING_B64"'"' -i src/infra/eks/api/01-products-api-secret.yaml || { echo "Error updating msslq-connection-string value"; exit 1; }
+      - name: Create/Update Secrets
+        env:
+          ConnectionStrings__DefaultConnection: Server=${{ secrets.DB_INSTANCE_PRODUTOS }},${{ vars.DB_PORT }};Database=SnackTechProductsDb;User=${{ secrets.DB_UID_PRODUTOS }};Password=${{ secrets.DB_PASSWORD_PRODUTOS }};TrustServerCertificate=True
+        run: |
+          kubectl create secret generic api-orders-secret \
+            --from-literal=ConnectionStrings__DefaultConnection="$ConnectionStrings__DefaultConnection"
       
-  #     - name: Replace ECR image string value
-  #       env:
-  #         IMAGE_URI: ${{ steps.build-image.outputs.image }}
-  #       run: |
-  #         yq e '.spec.template.spec.containers[0].image = "'"$IMAGE_URI"'"' -i src/infra/eks/api/02-products-api-deployment.yaml || { echo "Error updating ecr_image_url_repo_tag value"; exit 1; }
-  #     - name: Deploy to EKS
-  #       run: |
-  #         kubectl apply -f src/infra/eks/api
+      - name: Create/Update ConfigMap
+        env:
+          ProdutoApiSettings__UrlBase: api-payment-service:8080/api
+          PagamentoApiSettings__UrlBase: api-products-service:8080/api
+        run: |
+          kubectl create configmap api-orders-configmap \
+            --from-literal=ProdutoApiSettings__EnableIntegration="true" \
+            --from-literal=ProdutoApiSettings__UrlBase="$ProdutoApiSettings__UrlBase" \
+            --from-literal=PagamentoApiSettings__EnableIntegration="true" \
+            --from-literal=PagamentoApiSettings__UrlBase="$PagamentoApiSettings__UrlBase"
+          
+      - name: Replace ECR image string value
+        env:
+          IMAGE_URI: ${{ steps.build-image.outputs.image }}
+        run: |
+          yq e '.spec.template.spec.containers[0].image = "'"$IMAGE_URI"'"' -i k8s/01-orders-api-deployment.yaml || { echo "Error updating ecr_image_url_repo_tag value"; exit 1; }
+      
+      - name: Deploy to EKS
+        run: |
+          kubectl apply -f k8s
